# Generated by Django 3.0 on 2019-12-13 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('listaCompras', '0002_producto_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.PerfilUsuario'),
        ),
    ]
