# Generated by Django 3.0 on 2019-12-13 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('listaCompras', '0003_auto_20191213_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='title',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='producto',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.PerfilUsuario'),
        ),
    ]
