# Generated by Django 3.0 on 2019-12-13 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('listaCompras', '0005_auto_20191213_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.PerfilUsuario'),
        ),
        migrations.CreateModel(
            name='ListaDeCompras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listaCompras.Producto')),
            ],
        ),
    ]
