# Generated by Django 3.0 on 2019-12-17 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('listaCompras', '0006_auto_20191213_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='creador',
        ),
        migrations.AddField(
            model_name='listadecompras',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.PerfilUsuario'),
        ),
    ]
