# Generated by Django 3.0 on 2019-12-18 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('listaCompras', '0007_auto_20191217_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadecompras',
            name='nombre_lista',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='listadecompras',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.PerfilUsuario'),
        ),
        migrations.RemoveField(
            model_name='listadecompras',
            name='productos',
        ),
        migrations.AddField(
            model_name='listadecompras',
            name='productos',
            field=models.ManyToManyField(to='listaCompras.Producto'),
        ),
    ]
