# Generated by Django 3.0 on 2019-12-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaCompras', '0008_auto_20191218_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listadecompras',
            name='productos',
        ),
        migrations.AddField(
            model_name='listadecompras',
            name='cantidad_productos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
