# Generated by Django 3.0 on 2019-12-18 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listaCompras', '0009_auto_20191218_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listadecompras',
            name='cantidad_productos',
        ),
    ]
